<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" name="Command line test" tests="4" failures="2" timestamp="27 Jul 2018 15:45:31 GMT" time="3.237" errors="0">
  <testcase name="getAllOrganization" time="1.481" classname="com.intentwise.apitest.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [301] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [301] but found [401]
	at com.intentwise.apitest.LoginTest.getAllOrganization(LoginTest.java:125)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- getAllOrganization -->
  <testcase name="getUser" time="0.457" classname="com.intentwise.apitest.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [301] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [301] but found [401]
	at com.intentwise.apitest.LoginTest.getUser(LoginTest.java:98)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- getUser -->
  <testcase name="loginFailure" time="0.583" classname="com.intentwise.apitest.LoginTest"/>
  <testcase name="loginSuccess" time="0.701" classname="com.intentwise.apitest.LoginTest"/>
</testsuite> <!-- Command line test -->
